name: "Java app build"
description: "A building action for java project"
inputs:
   java_version:
      description: "Java version for building"
      required: true
      default: '21'
   skip_test:
      description: "Skip the test"
      required false
      default: false

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{inputs.java_version}}
      - name: Run Unit Tests
        if: ${{ inputs.skip-tests == 'false' }}
        run: mvn test
        shell: bash
        working-directory: ${{ inputs.working-directory }}
      - name: Run the Maven verify phase
        run: mvn --batch-mode install
      - name: Deploy artifact
        run: mvn --batch-mode deploy
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}