name: greetings

on: [issues]

jobs:
  hello_world:
      runs-on: ubuntu-latest
      permissions:
        issues: write
        pull-requests: write
      steps:
        - uses: actions/first-interaction@v1
          with:
            issue-message: "I am going to process your request soon"

