name: Build Java app

on: 
   push:
   workflow_dispatch:

jobs:
   build-java-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Run the Maven verify phase
        run: mvn --batch-mode install
      - name: Deploy artifact
        run: mvn --batch-mode deploy
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
