name: Build Java app

on: 
   workflow_dispatch:

jobs:
   build-java-app-without-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java-app
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/action
        with:
            java_version: '21'
            skip_test: true

   build-java-app-with-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java-app
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/action
        with:
            java_version: '21'
            skip_test: false
