name: Build Java app

on: push

jobs:
   build-java-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Run the Maven verify phase
        working-directory: java-app
        run: mvn install
      - name: Deploy artifact
        working-directory: java-app
        run: mvn deploy
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
